[project]
name = "enroll"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click==8.3.1",
    "docopt>=0.6.2",
    "openpyxl==3.1.5",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
]
