[project]
name = "enroll"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "openpyxl==3.1.5",
]

[dependency-groups]
dev = [
    "click==8.3.0",
    "pytest==9.0.1",
]
